language: ruby
bundler_args: --without development
rvm: 1.9.3

notifications:
  recipients:
    - rafe.hatfield@gmail.com

before_script:
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
#   - "psql -c 'create database dandelion_test;' -U postgres"
  bundle exec rake db:reset db:migrate db:test:prepare